name: Live Stream
on: [push, pull_request]

jobs:
  live_stream:
    runs-on: ubuntu-latest

    steps:
      - uses: AnimMouse/setup-yt-dlp@v1
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: cd ..
      - run: npm install
      - run: |
          npm start
