name: Download Video and Upload to VK
on:
  workflow_dispatch:
    inputs:
      youtube_id:
        required: true
        
jobs:
  live_stream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AnimMouse/setup-yt-dlp@v1
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - run: | 
         yt-dlp '${{ github.event.inputs.youtube_id }}' -P './videos' -o '%(title)s [%(id)s] [%(channel_id)s].%(ext)s'
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: npm install
      - run: |
          node main.js
