name: Download Video and Upload to VK
on:
  workflow_dispatch:
    inputs:
      youtube_id:
        required: true
        
jobs:
  live_stream:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AnimMouse/setup-yt-dlp@v1
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - run: |
         sudo apt install aria2 -y
      - run: | 
         yt-dlp -f '((bv*[fps>30]/bv*)[height<=720]/(wv*[fps>30]/wv*)) + ba / (b[fps>30]/b)[height<=720]/(w[fps>30]/w)[protocol!*=dash]' --merge-output-format mkv -P './videos' -o '%(title)s [%(id)s] [%(channel_id)s].%(ext)s' --external-downloader=aria2 --external-downloader-args '-j 16 -x 16 -s 16 -k 1M' --no-warnings --progress --throttled-rate 100K '${{ github.event.inputs.youtube_id }}'
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: npm install
      - run: |
          node main.js
