name: Recording 
on:
  workflow_dispatch:
    inputs:
      youtube_id:
        required: true
        
jobs:
  live_stream:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
#       - uses: AnimMouse/setup-yt-dlp@v1
      - uses: FedericoCarboni/setup-ffmpeg@v1
#       - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
#       - uses: actions/setup-go@v2
#       - run: go install 'github.com/Kethsar/ytarchive@master'
      - run: dir
      - run: ytarchive.exe --wait -r 180 -o 'videos/%(title)s [%(id)s] [%(channel_id)s]' --debug -c cookies.txt --add-metadata --threads 8 --save --t --mkv '${{ github.event.inputs.youtube_id }}' 720p/720p60
      - run: npm install
      - run: |
          node main.js
